# Generated by Django 4.0.3 on 2022-03-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Table_Number', max_length=100)),
                ('selected_table_number', models.IntegerField(default=0)),
            ],
        ),
    ]
