# Generated by Django 4.0.3 on 2022-03-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='table_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
