# Generated by Django 4.0.3 on 2022-03-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_dashboardmodel_id_dashboardmodel_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmodel',
            name='name',
            field=models.CharField(default='Table_Number', max_length=100),
        ),
    ]
